initial set of calculators
auperatech/VMSS2.0 pull request #8
Opened 2024-02-22 23:06 UTC by MatthewWiens101

- [ ] add documentation for all calculators (inputs, outputs, conditions)
- [ ] add clarification on packets which can be converted to other packets automatically

2024-02-28 05:45 UTC, milaniez requested changes

2024-02-28 05:45 UTC, milaniez commented on docs/node_input_output_guide.md
> +**Basic Node IO:** This node has no input streams, rather the input is set by providing a url through `node_options->demux->input_url` (TODO check that this is the only way). This node can have 1 or
not the only way. other way is by adding graph_input and use input_url

2024-02-28 05:45 UTC, milaniez commented on docs/node_input_output_guide.md
> +**Basic Node IO:** This node has two input streams, the first takes `VideoPacket` objects, and the second takes `AVCodecContextPacket` objects, which are treated as side packets. This node has no out
same as above (graph_output)

2024-02-28 05:45 UTC, milaniez commented on docs/node_input_output_guide.md
> +**Basic Node IO:** In its base configuration (`node_options->op_mode` is OP_MODE_ANY (0)), this node can have any number of input streams, which must take packet objects that inherit from `PacketBase
this is correct

2024-02-28 21:38 UTC, YZhangAupera commented on docs/node_input_output_guide.md
> +**Side Packets:** A side packet is a stream that is intended to pass a single, constant, value. When a stream is treated as a side packet, a node will take the first packet arriving from that stream
does this mean a side packet stream unsynced and mutable?

2024-02-28 21:38 UTC, YZhangAupera commented on docs/node_input_output_guide.md
> +**Mutability:** If a stream is mutable, then content in the packets may be modified, such as editing the image in an `ImagePacket` object. This is generally doo save space on the device as large pack
is "doo" a typo of "to"?

2024-02-28 21:55 UTC, YZhangAupera commented on docs/node_input_output_guide.md
> +
The description here is very clear to me, but I wonder if structuring it with bullet points would make it easier to read, e.g.,
- Basic Node IO；
    - 3-input-stream mode
        1. TrackPacket
        2. VideoStreamInfoPacket
        3. UInt64Packet (side packets)
    - 4-input-stream mode
        ...

Moreover, should we have a table summarizing all input and output streams of the nodes so that a user can quickly refer to them?

2024-02-28 22:51 UTC, YZhangAupera commented on docs/node_input_output_guide.md
> +This node in its base configuration has 1 output stream, which produces `JsonPacket` objects. It optionally has two additional output streams so that the total number of output streams can also be 2
The first stream is for LPR notification and the third packet (optional) is for MLOps notification. They are both `JsonPacket` but their contents are different.

2024-02-28 23:03 UTC, YZhangAupera commented on docs/node_input_output_guide.md
> +**Description:** Records and saves a clips generated from incoming image packets. Receives ClipGeneratorCommandPacket entries which tell it to start or stop recording.
ClipGeneratorCommandPacket -> `ClipGeneratorCommandPacket`

2024-02-28 23:19 UTC, YZhangAupera commented on docs/node_input_output_guide.md
> +- if an entry of `node_options->input_attrs` or `node_options->output_attrs` has has_packet_on_init not equal to 0, then corresponding pool_size must be 1
has_packet_on_init -> `has_packet_on_init`
pool_sz -> `pool_sz`

2024-02-28 23:43 UTC, YZhangAupera commented on docs/node_input_output_guide.md
> +## subgraph
I'm not very familiar with the node Subgraph and the corresponding sub-nodes (host_sink and host_source). Maybe we need some graphs for better illustration somewhere else if this document is just about node IO

2024-02-29 00:45 UTC, MatthewWiens101 commented on docs/node_input_output_guide.md
> +**Basic Node IO:** In its base configuration (`node_options->op_mode` is OP_MODE_ANY (0)), this node can have any number of input streams, which must take packet objects that inherit from `PacketBase
great thanks!

2024-02-29 02:02 UTC, MatthewWiens101 commented on docs/node_input_output_guide.md
> +## subgraph
agreed. this will not be in the documentation for kria-som, but for the future it is important. We are thinking of incorporating pbtxt examples for every node somehow.

2024-02-29 02:06 UTC, MatthewWiens101 commented on docs/node_input_output_guide.md
> +## Stream Types
agreed. it will be removed

2024-02-29 02:07 UTC, MatthewWiens101 commented on docs/node_input_output_guide.md
> +**Mutability:** If a stream is mutable, then content in the packets may be modified, such as editing the image in an `ImagePacket` object. This is generally doo save space on the device as large pack
should be done to. however this section will be removed

2024-02-29 04:13 UTC, MatthewWiens101 commented on docs/node_input_output_guide.md
> +
I have switched to a bullet point format which is hopefully easier to read and reference. The table idea is great, but we may only get around to it if there is enough time.

2024-02-29 04:14 UTC, MatthewWiens101 commented on docs/node_input_output_guide.md
> +**Side Packets:** A side packet is a stream that is intended to pass a single, constant, value. When a stream is treated as a side packet, a node will take the first packet arriving from that stream
Hopefully the removal of the details on synced and mutability helps avoid confusion

2024-03-01 02:55 UTC, merged